{% set version = "0.8.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rncl
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rncl_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rncl/rncl_{{ version }}.tar.gz
  sha256: 1d876e4f5f2b8a24cc3ea1002c29eedbc0ca96011b0fa15b085e5b75cfc7993a

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=0.11.0
    - r-progress >=1.1.2
  run:
    - r-base
    - r-rcpp >=0.11.0
    - r-progress >=1.1.2

test:
  commands:
    - $R -e "library('rncl')"           # [not win]
    - "\"%R%\" -e \"library('rncl')\""  # [win]

about:
  home: https://github.com/fmichonneau/rncl
  license: BSD-2-Clause
  summary: An interface to the Nexus Class Library which allows parsing of NEXUS, Newick and other phylogenetic tree file formats. It provides elements of the file that can be used to build phylogenetic objects such as ape's 'phylo' or phylobase's 'phylo4(d)'. This functionality is demonstrated with 'read_newick_phylo()'
    and 'read_nexus_phylo()'.
  license_family: BSD
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_2_clause
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
