travis:
  secure:
    BINSTAR_TOKEN: b8NPu2yv+7tM9hhSsp1LNwMRnm6Knq1GZlZo/yLv9pc5/LxLm2TxbZjGZ+1KzQvvrM2Z5xE9Sxmpq5g8dJm2vhrk+0MJ4XqDy6GFF8f1DL1Uw8scdW583+PjDiOdjJ/wy+/P9I73rKgJQO0u4ELga904cs8c6/ZwfwzdbIBulRvcSay+lbXR+NXwIQKr6PxXfrnN4Y1XTRfRbbK6ioDROCspanrEqbjktGchH1AUlNcm703d5xf/YEdWGOJs026EJNMqXe1G24/Pbnyt1kMxBtuUAdlEQB6ovz6MtWMV8LHVoBv9SPx/+Lin+qzIr09k4zvazF+aToAmqeza14aXjkA6xwhsLvHX7EXeNWRO7f2nRRMkR/2R4lNvxxed2nHsR7p/53IoV0IFOQxeq+QBrZe61I1D/TadnCu30i615583U7WH8uF5BrxXkG8U1SeLvZ2q5sN4m47OO8Lnu/c22hcj+bC6ZOWuRaSI79THWyXjsfSGpZ6wFSNAoCOcoPhuyojd2CJspCw5czHcxyTSTvWgszY8oGNtinG2RHf2nSMkrOSYi2qwO9A9s+IgCr9CrKhq6mzWIviaRak5fowW1Q5pji3Y9p0UPjbuTbKDUqK/F22JygM+wCUBzJRwLdWkG/CtTd4gX2dKZMHux+CdO6OJKzb3COu1wro5e6j2yyI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
